In [1]:
import tensorflow as tf

/home/wklee/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [6]:
a = tf.placeholder(tf.float32, shape=[3]) # shape can be None...which allows data with any shape
b = tf.constant([5, 5, 5], tf.float32)
# use the placeholder as you would a constant or a variable
c = a + b  # short for tf.add(a, b)

data_list = [{a: [1,2,3]}, {a: [4,5,6]}, {a: [7,8,9]}]
with tf.Session() as sess:
    for a_dict in data_list:
        print(sess.run(c, feed_dict=a_dict)) 

[6. 7. 8.]
[ 9. 10. 11.]
[12. 13. 14.]
